# Generated by Django 2.2.12 on 2020-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeclient',
            name='service_n',
            field=models.TextField(blank=True, null=True),
        ),
    ]
