# Generated by Django 2.2.12 on 2021-01-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0002_auto_20200715_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeclient',
            old_name='last_service',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='storeclient',
            name='avarage_expense',
        ),
        migrations.RemoveField(
            model_name='storeclient',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='storeclient',
            name='hair_lenght',
        ),
        migrations.RemoveField(
            model_name='storeclient',
            name='service_n',
        ),
    ]
