# Generated by Django 2.2.12 on 2021-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0003_auto_20210129_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeclient',
            name='credit',
            field=models.IntegerField(default=1),
        ),
    ]
