# Generated by Django 2.2.12 on 2021-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0004_storeclient_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeclient',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
