# Generated by Django 2.2.12 on 2021-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0006_auto_20210208_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeclient',
            name='isMember',
            field=models.BooleanField(default=False),
        ),
    ]
