# Generated by Django 2.2.12 on 2021-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0008_auto_20210226_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeclient',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
