# Generated by Django 2.2.12 on 2021-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclients', '0009_auto_20210226_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeclient',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
