# Generated by Django 2.2.12 on 2020-10-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0012_store_display_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
