# Generated by Django 2.2.12 on 2021-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
