# Generated by Django 2.2.12 on 2021-02-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_addon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='id_c',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
