# Generated by Django 2.2.12 on 2021-04-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_addon_id_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='id_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
