# Generated by Django 2.2.12 on 2020-05-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_remove_store_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('max_n', models.IntegerField()),
                ('color', models.IntegerField()),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store')),
            ],
        ),
    ]
