# Generated by Django 2.2.12 on 2020-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200708_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstore',
            name='duration_book',
            field=models.IntegerField(null=True),
        ),
    ]
