# Generated by Django 2.2.12 on 2020-08-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesstore_duration_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesstore',
            name='duration_book',
        ),
    ]
