# Generated by Django 2.2.12 on 2020-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201002_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesstore',
            name='price',
            field=models.IntegerField(),
        ),
    ]
