# Generated by Django 2.2.12 on 2020-10-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicesstore_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesstore',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
