# Generated by Django 2.2.12 on 2020-10-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201028_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesstore',
            name='display',
        ),
    ]
