# Generated by Django 2.2.12 on 2020-10-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_servicesstore_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstore',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
