# Generated by Django 2.2.12 on 2021-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicesstore_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstore',
            name='hasToBeCLient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesstore',
            name='hasToBeMember',
            field=models.BooleanField(default=False),
        ),
    ]
