# Generated by Django 2.2.12 on 2021-04-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20210426_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesstore',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_category.ServiceCategory'),
        ),
    ]
