# Generated by Django 2.2.12 on 2021-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20210426_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstore',
            name='price_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
