# Generated by Django 2.2.12 on 2020-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
