# Generated by Django 2.2.12 on 2020-10-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
        ('services', '0007_auto_20201002_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.AddOn')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesStore')),
            ],
        ),
    ]
