# Generated by Django 2.2.12 on 2021-04-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceaddons', '0002_serviceaddon_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaddon',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
