# Generated by Django 2.2.12 on 2021-04-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0012_auto_20210201_1820'),
        ('store', '0029_auto_20210329_1233'),
        ('shopclients', '0010_storeclient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesStore')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
                ('store_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopclients.StoreClient')),
            ],
        ),
    ]
