# Generated by Django 2.2.12 on 2021-04-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customservice',
            name='name',
        ),
    ]
