# Generated by Django 2.2.12 on 2020-05-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='payment_method',
        ),
    ]
