# Generated by Django 2.2.12 on 2020-07-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_store_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
