# Generated by Django 2.2.12 on 2020-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200708_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
