# Generated by Django 2.2.12 on 2020-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
