# Generated by Django 2.2.12 on 2020-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
