# Generated by Django 2.2.12 on 2020-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200811_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
