# Generated by Django 2.2.12 on 2020-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
