# Generated by Django 2.2.12 on 2020-09-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200828_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display_1',
            field=models.BooleanField(default=False),
        ),
    ]
