# Generated by Django 2.2.12 on 2020-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_store_display_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
