# Generated by Django 2.2.12 on 2021-01-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_store_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='closed_message',
            field=models.CharField(default='Siamo spiacenti, al momento siamo chiusi!', max_length=100),
        ),
    ]
