# Generated by Django 2.2.12 on 2021-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210126_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('closed', 'business_type')},
        ),
        migrations.AlterField(
            model_name='store',
            name='closed_message',
            field=models.CharField(default='Siamo spiacenti, al momento siamo chiusi!', max_length=150),
        ),
    ]
