# Generated by Django 2.2.12 on 2021-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210126_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closed_message',
            field=models.CharField(default='Siamo spiacenti, al momento siamo chiusi! Non appena riapriremo saremo  prenotabili online!', max_length=150),
        ),
    ]
