# Generated by Django 2.2.12 on 2021-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210126_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='credits',
            field=models.BooleanField(default=False),
        ),
    ]
