# Generated by Django 2.2.12 on 2021-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_store_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='order_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
