# Generated by Django 2.2.12 on 2021-02-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_store_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='must_pay',
            field=models.BooleanField(default=False),
        ),
    ]
