# Generated by Django 2.2.12 on 2021-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_store_must_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='adons',
            field=models.BooleanField(default=False),
        ),
    ]
