# Generated by Django 2.2.12 on 2021-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_store_adons'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='quarter_displ',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='table_font_size',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='store',
            name='table_line_heigth',
            field=models.IntegerField(default=60),
        ),
    ]
