# Generated by Django 2.2.12 on 2021-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210222_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
