# Generated by Django 2.2.12 on 2021-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_store_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='available_on',
            field=models.CharField(choices=[('a', 'Always available'), ('f', 'Full hours'), ('q', 'Quater hours')], default='q', max_length=1),
        ),
    ]
