# Generated by Django 2.2.12 on 2021-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_store_available_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='five_displ',
            field=models.BooleanField(default=False),
        ),
    ]
