# Generated by Django 2.2.12 on 2021-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_store_five_displ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='table_font_size',
            field=models.IntegerField(default=12),
        ),
    ]
