# Generated by Django 2.2.12 on 2021-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_store_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='book_advance',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='store',
            name='cancel_advance',
            field=models.IntegerField(default=2),
        ),
    ]
