# Generated by Django 2.2.12 on 2021-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210329_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_category',
            field=models.BooleanField(default=False),
        ),
    ]
