# Generated by Django 2.2.12 on 2021-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_store_update_price_scroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='only_app',
            field=models.BooleanField(default=False),
        ),
    ]
