# Generated by Django 2.2.12 on 2020-09-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripedata',
            old_name='data',
            new_name='data_string',
        ),
    ]
