# Generated by Django 2.2.12 on 2020-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20200915_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedata',
            name='hook_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
