# Generated by Django 2.2.12 on 2020-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_stripedata_hook_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedata',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
