# Generated by Django 2.2.12 on 2020-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailconfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='shop',
            field=models.CharField(default='wellens CLinic', max_length=50),
            preserve_default=False,
        ),
    ]
