# Generated by Django 2.2.12 on 2020-08-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeshour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshour',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
