# Generated by Django 2.2.12 on 2020-08-31 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeshour', '0002_auto_20200831_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshour',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
