# Generated by Django 2.2.12 on 2021-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeshour', '0004_auto_20200831_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshour',
            name='end_t',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshour',
            name='start_t',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
