# Generated by Django 2.2.12 on 2020-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
