# Generated by Django 2.2.12 on 2020-08-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='store_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
