# Generated by Django 2.2.12 on 2020-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookings_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='store_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
