# Generated by Django 2.2.12 on 2020-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200907_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last login'),
        ),
    ]
