# Generated by Django 2.2.12 on 2020-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookings_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
