# Generated by Django 2.2.12 on 2021-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='recurring_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
