# Generated by Django 2.2.12 on 2021-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_bookings_recurring_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payed',
            field=models.IntegerField(default=False),
        ),
    ]
