# Generated by Django 2.2.12 on 2021-02-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_bookings_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
