# Generated by Django 2.2.12 on 2021-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20210209_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
