# Generated by Django 2.2.12 on 2021-02-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookings_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
