# Generated by Django 2.2.12 on 2021-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20210322_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='day_to_delete',
            field=models.IntegerField(default=2),
        ),
    ]
