# Generated by Django 2.2.12 on 2021-04-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_bookings_day_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_on_plt',
            field=models.BooleanField(default=False),
        ),
    ]
