# Generated by Django 2.2.12 on 2021-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_bookings_booked_on_plt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='store_client',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
