# Generated by Django 2.2.12 on 2021-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_bookings_store_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='store_client',
            field=models.IntegerField(default=1),
        ),
    ]
