# Generated by Django 2.2.12 on 2021-04-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0029_auto_20210329_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
