# Generated by Django 2.2.12 on 2020-05-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_remove_store_payment_method'),
        ('services', '0001_initial'),
        ('employeeservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservices',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServicesStore'),
        ),
        migrations.AddField(
            model_name='employeeservices',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store'),
        ),
    ]
